spring.application.name=horte-api

spring.datasource.url=jdbc:postgresql://localhost:5432/horteDB
spring.datasource.username=postgres
spring.datasource.password=noteBOOK_32
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do JPA/Hibernate
# Trocar de update para none quanndo terminar
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Configurações de segurança

jwt.secret=a5B7p00q2r4s6t8u0v2w4x6y8z0a2b4c6d8o8p0q2r4s6t8u0v2u0v2w4x6y8z0a2b4c6d8e0f2g4h6i6j86i6j8k0l2m4n6o8p0q2r4s6t8u0v2w4x6y8z0a2b4c6d8e0f2g4h6i6j8k0l2m4n6o8p0q2r4s6t8u0
# Tempo de expiração do tokeln
jwt.expirationMs=86400000